# Generated by Django 3.1 on 2020-08-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200823_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('passenger', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='flights.flight')),
            ],
        ),
    ]
