# Generated by Django 3.1 on 2020-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger',
            field=models.ManyToManyField(blank=True, related_name='passenger', to='flights.Flight'),
        ),
    ]
